function xlabels_offset(ha,tcks,labels,offset)

haNew=axes('position',ha.Position,...
           'xlim',ha.XLim,...
           'ylim',ha.YLim,...
           'TickLength',[0 0],...
           'color','none');
d=diff(tcks);
d=[d;d(end)];
x=tcks+offset*d;

set(haNew,'xtick',x,'xticklabel',labels);
